/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Calculator.Control_Calculator;
import util.FlujoOutPut;

/**
 *
 * @author huesped
 */
public class Calculator extends java.awt.Frame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadena = new javax.swing.JLabel();
        botonCalculator = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaOutPut1 = new Vista.TextAreaOutPut();
        jScrollPane1 = new javax.swing.JScrollPane();
        textCadena = new javax.swing.JTextArea();

        setResizable(false);
        setTitle("Calculator String");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        cadena.setText("Cadena");

        botonCalculator.setLabel("Calcular");
        botonCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalculatorActionPerformed(evt);
            }
        });

        textAreaOutPut1.setBorder(javax.swing.BorderFactory.createTitledBorder("OutPut Message"));
        textAreaOutPut1.setColumns(20);
        textAreaOutPut1.setEditable(false);
        textAreaOutPut1.setForeground(java.awt.Color.blue);
        textAreaOutPut1.setRows(5);
        jScrollPane2.setViewportView(textAreaOutPut1);

        textCadena.setColumns(20);
        textCadena.setRows(5);
        jScrollPane1.setViewportView(textCadena);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cadena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(botonCalculator)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadena)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCalculator)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cadena.getAccessibleContext().setAccessibleName("cadena");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void botonCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalculatorActionPerformed
        
            FlujoOutPut flujo=new FlujoOutPut(this.textAreaOutPut1);
            System.setOut(flujo);
            System.setErr(flujo);
            this.textAreaOutPut1.setText("");
            String valor=this.textCadena.getText();
            int suma=Control_Calculator.add(valor);
            System.out.println("la suma es: "+suma);       
    }//GEN-LAST:event_botonCalculatorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalculator;
    private javax.swing.JLabel cadena;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private Vista.TextAreaOutPut textAreaOutPut1;
    private javax.swing.JTextArea textCadena;
    // End of variables declaration//GEN-END:variables
}
